services:
  api:
    image: pdfretriver:lastest
    build: .
    container_name: fastapi-application
    depends_on:
      - mongodb
    ports:
      - 4023:8000
    env_file:
      - .env
    volumes:
      - .:/opt
    restart: "no"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    # command: tail -f /dev/null

  
  mongodb:
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - D:/containerdbfiles:/data/db
volumes:
  mongo_data:

# networks:
#   app-network:
#     driver: bridge